# Generated by Django 4.0.6 on 2022-08-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0002_remove_dish_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
