# Generated by Django 4.0.6 on 2022-08-02 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0005_restaurantlike_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentDayMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(auto_created=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_service.menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_service.restaurant')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
