# Generated by Django 4.0.6 on 2022-08-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0006_currentdaymenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentdaymenu',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={},
        ),
        migrations.AlterModelOptions(
            name='drink',
            options={},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={},
        ),
        migrations.AlterField(
            model_name='currentdaymenu',
            name='datetime',
            field=models.DateField(auto_created=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='menu',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.ManyToManyField(to='menu_service.menu'),
        ),
    ]
