# Generated by Django 4.0.6 on 2022-08-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0007_alter_currentdaymenu_options_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='about',
            field=models.CharField(default='ansajdnas', max_length=255),
            preserve_default=False,
        ),
    ]
