# Generated by Django 4.0.6 on 2022-08-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0008_menu_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='restaurant_name',
        ),
    ]
